# Generated by Django 5.2.12 on 2026-04-03 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(blank=True, help_text='For heatmap (decimal degrees)', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='For heatmap (decimal degrees)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proof_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('urgency', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5)),
                ('detected_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('killed', 'Killed')], default='open', max_length=20)),
                ('final_event_date', models.DateTimeField(blank=True, null=True)),
                ('before_after', models.TextField(blank=True, help_text='Describe before vs after the intervention')),
                ('total_need', models.TextField(blank=True, help_text='Overall community need summary')),
                ('community_reaction', models.TextField(blank=True, help_text='Community feedback / emoji reactions')),
                ('killed_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_volunteers', models.ManyToManyField(blank=True, related_name='interested_in', to=settings.AUTH_USER_MODEL)),
                ('selected_volunteers', models.ManyToManyField(blank=True, related_name='selected_for', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_problems', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communityproblems', to='NeedsMeshApp.locality')),
                ('proof_images', models.ManyToManyField(blank=True, to='NeedsMeshApp.proofimage')),
            ],
            options={
                'ordering': ['-urgency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_data_json', models.JSONField(blank=True, default=dict)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('field_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='NeedsMeshApp.communityproblem')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Organisation Admin'), ('field_worker', 'Field Worker'), ('volunteer', 'Volunteer')], default='volunteer', max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('has_badge', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
