# Generated by Django 5.2.12 on 2026-04-03 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeedsMeshApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Nutrition'), ('health', 'Health & Medical'), ('education', 'Education'), ('shelter', 'Shelter & Housing'), ('water', 'Water & Sanitation'), ('livelihood', 'Livelihood & Employment'), ('disability', 'Disability Support'), ('elderly', 'Elderly Care'), ('child', 'Child Welfare'), ('environment', 'Environment'), ('disaster', 'Disaster Relief'), ('other', 'Other')], help_text='For Volunteers', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='NeedsMeshApp.locality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ngo_name',
            field=models.CharField(blank=True, help_text='For Field Workers', max_length=200, null=True),
        ),
    ]
